language: node_js
branches:
  only:
    - master
node_js:
  - v12.13.0
env:
  - SOCKET_PORT=8989 REACT_APP_SOCKET_URL='ws://localhost:8989' CI=false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success:
  - pip install --user codecov
  - export CODECOV_TOKEN="b56dc3ef-b18a-4704-974e-eab6bb981feb"
  - codecov --file coverage/lcov.info --disable search
script:
  - yarn && yarn test --coverage
