language: node_js
branches:
  only:
    - master
    - stable
node_js:
  - v12.13.0
env:
  - SOCKET_PORT=8989 REACT_APP_SOCKET_URL='ws://localhost:8989' CI=false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test
  - yarn build
  - yarn build:electron
