import { actionTypes as sharedActions } from "../../shared/actions/actionTypes";

export const actionTypes = {
  //  actions from shared directory
  ...sharedActions,

  ADD_FLASH_MESSAGE: "ADD_FLASH_MESSAGE",
  REMOVE_FLASH_MESSAGE: "REMOVE_FLASH_MESSAGE",
  UPDATE_BASE_DATA: "UPDATE_BASE_DATA",
  DIGEST_APP_CREDITS: "DIGEST_APP_CREDITS",

  OPEN_EXTERNAL_LINK: "OPEN_EXTERNAL_LINK",
  DISPLAY_USER: "DISPLAY_USER",

  UPDATE_MY_USER_ID: "UPDATE_MY_USER_ID",
  UPDATE_MY_DOC_ID: "UPDATE_MY_DOC_ID",
  ADD_MY_SC_QUERY_ID: "ADD_MY_SC_QUERY_ID",
  REMOVE_MY_SC_QUERY_ID: "REMOVE_MY_SC_QUERY_ID",
  UPDATE_MY_SC_QUERY_ID: "UPDATE_MY_SC_QUERY_ID",

  //
  // websocket client actions
  //
  WS_BEGIN_RECONNECT: "REDUX_WEBSOCKET::BEGIN_RECONNECT",
  WS_RECONNECT_ATTEMPT: "REDUX_WEBSOCKET::RECONNECT_ATTEMPT",
  WS_RECONNECTED: "REDUX_WEBSOCKET::RECONNECTED",
  WS_BROKEN: "REDUX_WEBSOCKET::BROKEN",
  WS_CLOSED: "REDUX_WEBSOCKET::CLOSED",
  WS_ERROR: "REDUX_WEBSOCKET::ERROR",
  WS_MESSAGE: "REDUX_WEBSOCKET::MESSAGE",
  WS_OPEN: "REDUX_WEBSOCKET::OPEN",
  WS_CONNECT: "REDUX_WEBSOCKET::CONNECT",
  WS_SEND: "REDUX_WEBSOCKET::SEND"
};
