export const actionTypes = {
  // ====================================================
  //    INTERNAL ACTIONS
  // ====================================================

  DIGEST_APP_CREDITS: "DIGEST_APP_CREDITS",
  UPDATE_MY_USER_ID: "UPDATE_MY_USER_ID",

  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  REPLACE_USER_LIST: "REPLACE_USER_LIST",

  UPDATE_DOCUMENT: "UPDATE_DOCUMENT",

  ADD_SC_QUERY: "ADD_SC_QUERY",
  UPDATE_SC_QUERY: "UPDATE_SC_QUERY",
  DELETE_SC_QUERY: "DELETE_SC_QUERY",

  // ====================================================
  //    WEBSOCKET ACTIONS
  // ====================================================

  // Server dispatched actions:

  WS_BEGIN_RECONNECT: "REDUX_WEBSOCKET::BEGIN_RECONNECT",
  WS_RECONNECT_ATTEMPT: "REDUX_WEBSOCKET::RECONNECT_ATTEMPT",
  WS_RECONNECTED: "REDUX_WEBSOCKET::RECONNECTED",
  WS_BROKEN: "REDUX_WEBSOCKET::BROKEN",
  WS_CLOSED: "REDUX_WEBSOCKET::CLOSED",
  WS_ERROR: "REDUX_WEBSOCKET::ERROR",
  WS_MESSAGE: "REDUX_WEBSOCKET::MESSAGE",
  WS_OPEN: "REDUX_WEBSOCKET::OPEN",

  // Extra actions:
  WS_CREATE_USER_SUCCESS: "WS::CREATE_USER_SUCCESS",
  WS_CREATE_USER_ERROR: "WS::CREATE_USER_ERROR",
  WS_CREATE_USER_TIMEOUT: "WS::CREATE_USER_TIMEOUT",

  WS_GET_USER_LIST_SUCCESS: "WS::GET_USER_LIST_SUCCESS",
  WS_GET_USER_LIST_ERROR: "WS::GET_USER_LIST_ERROR",
  WS_GET_USER_LIST_TIMEOUT: "WS::GET_USER_LIST_TIMEOUT",

  WS_CREATE_DOCUMENT_SUCCESS: "WS::CREATE_DOCUMENT_SUCCESS",
  WS_CREATE_DOCUMENT_ERROR: "WS::CREATE_DOCUMENT_ERROR",
  WS_CREATE_DOCUMENT_TIMEOUT: "WS::CREATE_DOCUMENT_TIMEOUT",

  WS_CREATE_SC_QUERY_SUCCESS: "WS::CREATE_SC_QUERY_SUCCESS",
  WS_CREATE_SC_QUERY_ERROR: "WS::CREATE_SC_QUERY_ERROR",
  WS_CREATE_SC_QUERY_TIMEOUT: "WS::CREATE_SC_QUERY_TIMEOUT",

  WS_USER_JOINED: "WS::USER_JOINED",
  WS_USER_LEFT: "WS::USER_LEFT",

  // Client dispatched action types:

  WS_CONNECT: "REDUX_WEBSOCKET::CONNECT",
  WS_DISCONNECT: "REDUX_WEBSOCKET::DISCONNECT",
  WS_SEND: "REDUX_WEBSOCKET::SEND",

  // Extra actions:
  WS_CREATE_USER: "WS::CREATE_USER",
  WS_GET_USER_LIST: "WS::GET_USER_LIST",
  WS_CREATE_DOCUMENT: "WS::CREATE_DOCUMENT",
  WS_CREATE_SC_QUERY: "WS::CREATE_SC_QUERY",

  WS_USER_UPDATE: "WS::USER_UPDATE",
  WS_DOCUMENT_UPDATE: "WS::DOCUMENT_UPDATE"
};
