export const actionTypes = {
  //
  // Users scaffold
  //
  UPDATE_USER: "UPDATE_USER",
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  DESTROY_USER: "DESTROY_USER",
  REPLACE_USER_LIST: "REPLACE_USER_LIST",

  //
  // Documents scaffold
  //
  CREATE_DOCUMENT: "CREATE_DOCUMENT",
  UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  REPLACE_DOCUMENT_LIST: "REPLACE_DOCUMENT_LIST",

  //
  // ScQueries scaffold
  //
  CREATE_SC_QUERY: "CREATE_SC_QUERY",
  UPDATE_SC_QUERY: "UPDATE_SC_QUERY",
  DELETE_SC_QUERY: "DELETE_SC_QUERY",
  APPEND_SC_QUERY: "APPEND_SC_QUERY"
};
